trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - .gitignore

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'
  npmVersion: '10.x'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build Angular Library'
    steps:
    
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: $(nodeVersion)
    
    - task: Npm@1
      displayName: 'Install npm dependencies'
      inputs:
        command: 'install'
        workingDir: '.'
    
    - task: Npm@1
      displayName: 'Run unit tests'
      inputs:
        command: 'custom'
        customCommand: 'run test:ci'
        workingDir: '.'
    
    - task: Npm@1
      displayName: 'Build library'
      inputs:
        command: 'custom'
        customCommand: 'run build'
        workingDir: '.'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        pathToPublish: 'dist'
        artifactName: 'dist'
        publishLocation: 'Container'
